"""
Master script to generate ALL figures for the research paper.

Run this single script to generate all 8 figures at once.
"""

import subprocess
import sys
from pathlib import Path

def main():
    print("="*80)
    print("GENERATING ALL RESEARCH PAPER FIGURES")
    print("="*80)

    # Create results directory
    Path("results").mkdir(exist_ok=True)

    # Generate conceptual diagrams (Figures 1 & 2)
    print("\n[Step 1/2] Generating conceptual diagrams (Figures 1 & 2)...")
    try:
        subprocess.run([sys.executable, "generate_conceptual_figures.py"], check=True)
    except subprocess.CalledProcessError as e:
        print(f"  ✗ Error generating conceptual figures: {e}")
        return False

    # Generate data-driven figures (Figures 3 & 8)
    print("\n[Step 2/2] Generating data-driven figures (Figures 3 & 8)...")
    try:
        subprocess.run([sys.executable, "generate_paper_figures.py"], check=True)
    except subprocess.CalledProcessError as e:
        print(f"  ✗ Error generating data-driven figures: {e}")
        return False

    print("\n" + "="*80)
    print("ALL FIGURES GENERATED SUCCESSFULLY")
    print("="*80)

    # Summary
    figures = {
        "Figure 1": "results/figure1_circuit_diagram.png",
        "Figure 2": "results/figure2_methods_overview.png",
        "Figure 3": "results/figure3_baseline_distribution.png",
        "Figure 4": "results/activation_patching_layers.png",
        "Figure 5": "results/activation_patching_heads.png",
        "Figure 6": "results/logit_attribution.png",
        "Figure 7": "results/logit_lens_average.png",
        "Figure 8": "results/figure8_individual_trajectories.png"
    }

    print("\n📊 Figure Inventory:")
    for name, path in figures.items():
        exists = "✅" if Path(path).exists() else "❌"
        print(f"  {exists} {name}: {path}")

    # Check if any are missing
    missing = [name for name, path in figures.items() if not Path(path).exists()]

    if missing:
        print(f"\n⚠️  WARNING: {len(missing)} figure(s) not found:")
        for name in missing:
            print(f"     - {name}")
        print("\n   Figures 4-7 are generated by the notebook.")
        print("   Run the notebook to generate them:")
        print("   jupyter nbconvert --to notebook --execute notebooks/ioi_replication_validation.ipynb")
        return False
    else:
        print("\n✅ All 8 figures ready for publication!")
        return True

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
